spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    job:
      enabled: false

  data:
    mongodb:
      port: 0
      database: library
      #uri: mongodb://localhost:27017/db

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.work26.changelog
app:
  input-file: entries.csv
  output-author-file: authors.csv
  output-genre-file: genres.csv
  output-book-file: books.csv
  output-comment-file: comments.csv