GET http://localhost:8080/api/books/1/comments

###

GET http://localhost:8080/api/books/1/comments/1

###

POST http://localhost:8080/api/books/1/comments
Content-Type: application/json

{
  "comment": "New comment"
}

###


PUT http://localhost:8080/api/books/1/comments/3
Content-Type: application/json

{
  "comment": "New comment!!!"
}

###

DELETE http://localhost:8080/api/books/1/comments/8

###

DELETE http://localhost:8080/api/comments/2

###