DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, name VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, name VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    genre BIGINT NOT NULL,
    author BIGINT NOT NULL,
    FOREIGN KEY (genre) REFERENCES GENRES(id),
    FOREIGN KEY (author) REFERENCES AUTHORS(id)
    );

