DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT generated by default as identity, name VARCHAR(255) NOT NULL, primary key (id));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT generated by default as identity, name VARCHAR(255) NOT NULL, primary key (id));

DROP TABLE IF EXISTS comments;
create table comments (id bigint generated by default as identity, comment varchar(255) not null, book_id bigint NOT NULL, primary key (id));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT generated by default as identity,
    title VARCHAR(255) NOT NULL,
    genre BIGINT NOT NULL,
    author BIGINT NOT NULL,
    primary key (id),
    FOREIGN KEY (genre) REFERENCES GENRES(id),
    FOREIGN KEY (author) REFERENCES AUTHORS(id)
    );