DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(id UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY, name VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(id UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY, name VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS comments;
create table comments (id UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY, comment varchar(255) not null, book_id UUID NOT NULL);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    id UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    genre UUID NOT NULL,
    author UUID NOT NULL,
    FOREIGN KEY (genre) REFERENCES GENRES(id),
    FOREIGN KEY (author) REFERENCES AUTHORS(id)
    );