version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/db
    networks:
      nw:
  mongo:
    image: "mongo:4.4.4"
    ports:
      - "27018:27017"
    networks:
      nw:
networks:
  nw: